version: '3'
services:
  postgresql:
    image: postgres
    container_name: postgres
    volumes:
      - /var/lib/postgresql/
      - $PWD/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=topsecure
      - POSTGRES_DBNAME=api
    ports:
      - "5432:5432"
  nodeapp:
    image: loeken/kubernetes_nodejs_postgresql_demo:latest
    container_name: nodeapp
    depends_on:
      - postgresql
    #volumes:
    #  - $PWD:/usr/src/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=topsecure
      - POSTGRES_DBNAME=api
      - POSTGRES_HOST=postgresql
    ports:
      - "1337:1337"
